server:
  port: 8003
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cool_translator?useSSL=false
    username: translator
    password: translator
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
  cloud:
    function:
      definition: onTextExtractionError;onFileTranslationError
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          autoCreateTopics: false
          consumerProperties:
            allow.auto.create.topics: false
      bindings:
        onTextExtractionError-in-0:
          destination: json.cool_translator.file.extracted.error
          group: textExtractionErrorGroup
        onTextExtractionError-out-0:
          destination: json.cool_translator.translation_payment.refunded
        onFileTranslationError-in-0:
          destination: json.cool_translator.file.translated.error
          group: fileTranslationErrorGroup
        onFileTranslationError-out-0:
          destination: json.cool_translator.translation_payment.refunded